#
###################################
# Site wide configuration
####################################
#
title: Ece
email: ece@cyberstruggle.org
description: Cyber Struggle Researcher
url: https://eceorsel.github.io
baseurl: /


#
###################################
# Jekyll configuration
####################################
#
timezone:          UTC
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: "Ece Orsel"
  avatar: avatar.png
  job: "Cyber Struggle"
  bio: "Human Intelligence, Cyber Terrorism, Unconventional Warfare, Psychological Warfare"
  email: ece@cyberstruggle.org
  disqus-shortname: eceorsel
  twitter: eceburadayok
  facebook: #username
  google:
    plus: #username
    analytics: 
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: eceorsel
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: 
  xing: #username
  instagram: 
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: 
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
